# Generated by Django 3.2.19 on 2023-05-14 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_gameroom_is_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='owner',
        ),
    ]
